### ISSUE TITLE
themes small breakpoint view glitch / bug

### ISSUE THREAD

**Issue by luwes** [muxinc/player.style#39]
if you select the framework svelte in the left hand sidebar, the theme YT will disappear and you can see the render of the small view for a split second of the Demuxed 2022 theme and then the large view.

similarly this happens to the YT theme when going back.

this is a media-chrome issue caused by the setTimeout in the resize observer.

**Comment by heff** [comment]
Hmmm... Is this is unique enough situation that we really just need to fix it for player.style? Like is there a way to kick the resize observers for each theme whenever the filters change?

**Comment by luwes** [comment]
it's impossible to my knowledge to fix it in player.style. I wanted to discuss this in MCOH because we haven't been able to resolve this completely in the past. the quick fix is to remove the setTimeout here https://github.com/muxinc/media-chrome/blob/main/src/js/media-container.js#L375 which will remove the glitch but it introduces a non-fatal ResizeObserver error in the console in some rare cases, when CPU is constrained like in a Codesandbox.

**Comment by luwes** [comment]
fixed in https://github.com/muxinc/media-chrome/pull/960 ^^
