### ISSUE TITLE
Sutro Theme on Safari, no quality options 

### ISSUE THREAD

**Issue by heff** [muxinc/player.style#70]
<img width="411" alt="image" src="https://github.com/user-attachments/assets/bbade5f2-f614-4994-aaa1-0a20a7dce191">

1. Open Sutro in Safari
2. Click settings
3. Click quality
4. See that

**Comment by luwes** [comment]
is this on the home list page? there we set preload=none so the renditions are not available before playback.

we should hide the quality menu in this case and possibly the settings button if there are no submenus.
