### ISSUE TITLE
Theme view: Lanscape minimum size limited after viewing portrait size

### ISSUE THREAD

**Issue by heff** [muxinc/player.style#72]
1. View the theme viewer of a specific theme
2. Click the mobile/portrait view
3. Click back to the landscape view
4. Use the sizing slider to try to make it the smallest size

Expected: The player can still go down to ~300px wide
Result: The player can only be sized down to ~600px wide

**Comment by luwes** [comment]
does this happen always? I can't reproduce it at the moment.

I have seen it before though.

I see I used a timeout to start the dimension calculation, that could be the culprit.
https://github.com/muxinc/player.style/blob/1ec5d61b223138b1f668ec1d593189e2717a7279/site/app/_components/PlayerHero.tsx#L56-L62

I'll see if it can be done more reliably
